server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost/movie-service?createDatabaseIfNotExist=true&serverTimezone=UTC-3&useSSl=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
